// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUbfm7q-97eURorZj4sfgJqEc8vFfA4w',
    appId: '1:570583090389:web:060f5f26e8b0509433ce5c',
    messagingSenderId: '570583090389',
    projectId: 'lappy-fc381',
    authDomain: 'lappy-fc381.firebaseapp.com',
    storageBucket: 'lappy-fc381.firebasestorage.app',
    measurementId: 'G-TZLL3Q93BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_SvXFc0EWGrjUqQY_KljHTyyVO0F7Mk0',
    appId: '1:570583090389:android:188277d345720db633ce5c',
    messagingSenderId: '570583090389',
    projectId: 'lappy-fc381',
    storageBucket: 'lappy-fc381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnjcGEWPn9xxqGoQPdGWRMDO8H2fyWb7E',
    appId: '1:570583090389:ios:61e227d15d6115ee33ce5c',
    messagingSenderId: '570583090389',
    projectId: 'lappy-fc381',
    storageBucket: 'lappy-fc381.firebasestorage.app',
    iosBundleId: 'com.example.cricsonic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnjcGEWPn9xxqGoQPdGWRMDO8H2fyWb7E',
    appId: '1:570583090389:ios:61e227d15d6115ee33ce5c',
    messagingSenderId: '570583090389',
    projectId: 'lappy-fc381',
    storageBucket: 'lappy-fc381.firebasestorage.app',
    iosBundleId: 'com.example.cricsonic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVUbfm7q-97eURorZj4sfgJqEc8vFfA4w',
    appId: '1:570583090389:web:f73b68b34e802a4b33ce5c',
    messagingSenderId: '570583090389',
    projectId: 'lappy-fc381',
    authDomain: 'lappy-fc381.firebaseapp.com',
    storageBucket: 'lappy-fc381.firebasestorage.app',
    measurementId: 'G-4NDLCFQLR9',
  );

}